# Generated by Django 3.0.10 on 2020-09-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='STATUS_CHOICES',
            new_name='status',
        ),
    ]
